name: Continuous Integration Inicial
on: 
  pull_request:
    branches:
        - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@v8.7.0 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

