name: Discord
on:
  - push
jobs:
  Discord:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run Discord Webhook
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: Alertas Commit
          avatarUrl: https://domain/images/custom.png
          content: Um novo comit foi criado!
          severity: info # only to make sure the embed is added
          color: '#ff00aa'
          title: Commit
          description: "Um novo commit foi cirado"
          # details: not needed because we overrode default description.
          footer: This embed was brought to you by the letter R and the number 4.
          thumbnailUrl: https://domain/images/thumb.png
          imageUrl: https://domain/images/banner.png 


