name: Discord
on:
  - push
jobs:
  Discord:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run Discord Webhook
        uses: mrrobotdotapp/classic-discord-webhook@main
        with:
          id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: 'Commit Bot'


